@host1 = http://localhost:9080
@host2 = https://localhost:9443

###
GET {{host1}}/health

###
GET {{host1}}/app1/v1/api/sys/props

###
GET {{host1}}/app1/v1/api/sys

###
POST {{host1}}/app1/v1/api/sys
Content-Type: application/x-www-form-urlencoded

hostname=server2&heapSize=2024000&javaVersion=17&osName=Linux

###
POST {{host1}}/app1/v1/api/sys
Content-Type: application/x-www-form-urlencoded

hostname=server1&heapSize=1024000&javaVersion=11&osName=Windows

###
GET {{host2}}/app1/v1/api/sys/server1

###
DELETE {{host2}}/app1/v1/api/sys/server1
Authorization: Basic bob:321

###
GET {{host1}}/app1/v1/api/bonus

###
GET {{host1}}/app1/v1/api/bonus/JONES

###
GET http://localhost:9080/openapi/ui/

###
POST {{host1}}/app1/v1/auth/login
Content-Type: application/x-www-form-urlencoded

username=bob&password=1234

###
@jwt = Bearer 1234

###
GET {{host1}}/app1/v1/auth/rnd
Authorization: {{jwt}}